FROM androidsdk/android-31 

# 设置非交互模式，避免 apt 提示
ENV DEBIAN_FRONTEND=noninteractive

# 更新包列表并添加 deadsnakes PPA
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update

# 更新包列表并安装软件包
RUN apt-get update && \
    apt-get install -y \
    git \
    vim \
    patch \
    patchelf \
    wget \
    unzip \
    build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*  # 清理缓存

RUN git clone https://github.com/chaquo/chaquopy.git /app/chaquopy

# 下载并安装 Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3 && \
    rm Miniconda3-latest-Linux-x86_64.sh

# 初始化并创建环境
ENV PATH="/opt/miniconda3/bin:$PATH"

RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
RUN conda init bash && \
    /opt/miniconda3/bin/conda create -n py39 python=3.9 -y &&\
    /opt/miniconda3/bin/conda create -n py310 python=3.10 -y &&\
    /opt/miniconda3/bin/conda create -n py311 python=3.11 -y

# 默认激活
RUN echo 'conda activate py310' >> ~/.bashrc

SHELL ["/bin/bash", "-c"]
RUN /bin/bash -c "source /opt/miniconda3/etc/profile.d/conda.sh && \
    conda activate py39 && \
    python --version && \
    pip install --upgrade pip setuptools wheel && \
    pip install -r /app/chaquopy/server/pypi/requirements.txt &&\
    pip install numpy==1.25.0 &&\
    pip install setuptools_scm==8.1.0 &&\
    cd /app/chaquopy && \
    ./target/download-target.sh maven/com/chaquo/python/target/3.9.20-1"

SHELL ["/bin/bash", "-c"]
RUN /bin/bash -c "source /opt/miniconda3/etc/profile.d/conda.sh && \
    conda activate py310 && \
    python --version && \
    pip install --upgrade pip setuptools wheel && \
    pip install -r /app/chaquopy/server/pypi/requirements.txt &&\
    pip install numpy==1.25.0 &&\
    pip install setuptools_scm==8.1.0 &&\
    cd /app/chaquopy && \
    ./target/download-target.sh maven/com/chaquo/python/target/3.10.6-1"

SHELL ["/bin/bash", "-c"]
RUN /bin/bash -c "source /opt/miniconda3/etc/profile.d/conda.sh && \
    conda activate py311 && \
    python --version && \
    pip install --upgrade pip setuptools wheel && \
    pip install -r /app/chaquopy/server/pypi/requirements.txt &&\
    pip install numpy==1.25.0 &&\
    pip install setuptools_scm==8.1.0 &&\
    cd /app/chaquopy && \
    ./target/download-target.sh maven/com/chaquo/python/target/3.11.6-0"

SHELL ["/bin/bash", "-c"]
RUN /bin/bash -c "yes | sdkmanager --licenses && \
    yes | sdkmanager --install 'ndk;27.3.13750724'"

# 设置工作目录
WORKDIR /app

# 默认命令：启动构建，需要将项目挂载在/app/pyopenjtalk目录下
CMD ["/bin/bash"]